import type { Metadata } from "next";
import { GoogleAnalytics } from '@next/third-parties/google'
import Footer from "./footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Greenville Learning Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased'
      >
        {children}
        {Footer()}
      </body>
      <GoogleAnalytics gaId="G-K5LZGWBEHJ" />
    </html>
  );
}
